### ISSUE TITLE
Usability/Rendering Issues

### ISSUE THREAD

**Issue by chris0e3** [chrissimpkins/Hack#103]
Hack v2.010, TTF on OSX 10.8.
The following graphics (IMHO) shows some usability/rendering issues.

This is Source Code Pro 10.5pt.  (My current font.)
![sourcecodepro10 5](https://cloud.githubusercontent.com/assets/14280843/9859441/96dba5a0-5b1e-11e5-89db-b7c8f8f482a6.png)

This is Hack 10.5pt.  (I really like the greater x height, but the `()` looks like there’s a space between, similarly the `[` & `]` could be deeper, the `_` is too low, the initial, bold, `i` could look less like an `l` and the `‘` (U+2018) could be more distinct.)
![hack10 5](https://cloud.githubusercontent.com/assets/14280843/9859481/b71389a0-5b1e-11e5-8ccc-3a10cf8fcbbf.png)

This is Hack 10pt.  (This is unusable due to the initial `i` looking like an `l`, the blurred double quotes, the `~` is too flat & the `_` is too low & has bigger gap on the right.)
![hack10 0](https://cloud.githubusercontent.com/assets/14280843/9859503/d5e01baa-5b1e-11e5-8a5e-c57a22d5e2b9.png)

I think the alph-numerics look really good, but `#`, `<` & `>` could be better.

**Comment by chrissimpkins** [comment]
`()` do have additional sidebearing space.  This is intentional.  Have a look at it in source code rather than test text to see what you think.  It is intended to improve the legibility of parenthetic expressions in source.

Can you clarify what you mean by deeper on `[ ]`?

The underscores don't render as low for me on OS X 10.10.5 in Sublime Text: 

![underscores](https://cloud.githubusercontent.com/assets/4249591/9863618/b0389698-5b0f-11e5-88ce-43fbd7e7a216.png)

This occurs on some other platforms as well.  They are off center to the left and this has previously been reported.  I will fix this.

The double quotes don't render well at 10px.  Thanks for reporting this. It is the first that I've noticed it..  The grid isn't doing them any favors at that size.  At 9 and 11 they are much more clear:

9px 
![quotes-9](https://cloud.githubusercontent.com/assets/4249591/9863713/6315134a-5b10-11e5-9aa2-a0490b2a4854.png)

11px
![quotes-11](https://cloud.githubusercontent.com/assets/4249591/9863715/667a41fe-5b10-11e5-8040-f5ba39d12e0c.png)

I will need to see if I can add a bit of space to address this.  It looks like it could be the antialiasing causing the issue at that size.  Seems like they blur together.

The tilde problem has previously been reported and looks like it is an issue in Source Code Pro at that size as well.  

To my eye, the height of the `i` and `l` allow you to distinguish them at that size.  The point is apparent on OS X.  We are working on the hints for other platforms where certain text sizes render the point on the lowercase i right on top of the vertical stroke.  

For `#`, `<` and `>` can you expand on what you mean by better?  The pound sign has a bit more slant than the SCP glyph.  Are you looking for a more upright character?  The less than and greater than glyphs are more narrower in the vertical dimension than the corresponding ones in SCP.

**Comment by chris0e3** [comment]
> () do have additional sidebearing space. This is intentional. Have a look at it in source code rather than test text to see what you think. It is intended to improve the legibility of parenthetic expressions in source.

The screenshots were taken from Xcode.  I think they would look better if they curved more and, perhaps, were slightly taller.

> Can you clarify what you mean by deeper on [ ]?

I meant that the horizontals could be longer, making them less vertical-line like.

> The underscores don't render as low for me on OS X 10.10.5 in Sublime Text:

OK.  But they do in Xcode, TextWrangler, TextEdit & Terminal for me.

> To my eye, the height of the i and l allow you to distinguish them at that size.

Fine for Regular but less clear for Bold (unless the characters are adjacent).
Try again after 12 hours of pouring over 100,000 lines of code.
Perhaps a Hack-Medium or Semibold (halfway between Regular & Bold) would be better.

> For #, < and > can you expand on what you mean by better?

They are wider than necessary & tend to touch adjacent glyphs.

> Are you looking for a more upright character?

Yes.

Having changed Xcode to use Hack:
Also, the `*` could be lower (this is for code after all) & the `0` could have a smaller/lighter centre dot.
And `=` is slightly too wide such that `==` touches.
The `%` could be clearer - a longer diagonal.

**Comment by chrissimpkins** [comment]
Thanks for your feedback.  Noted.

**Comment by chrissimpkins** [comment]
I am working on a few problematic characters for the next release.  I hope to address the underscore & tilde in this release or the next.

**Comment by chrissimpkins** [comment]
The v2.014 test build addresses the underscore and tilde issues reported here.  Please give them a try and let me know what you think.  You can find the files in #111

**Comment by chrissimpkins** [comment]
> The v2.014 test build addresses the underscore and tilde issues reported here. Please give them a try and let me know what you think. You can find the files in #111 

These changes are now available in the general release v2.015.  Leaving the issue report open to address other issues contained here in the future.

**Comment by bkromhout** [comment]
I'm on OS X as well, a 15" retina MBP, and while I have no trouble with the ```i``` and ```l``` on the laptop's screen, when I'm using my external 1080p monitor, they can be a bit hard to distinguish in IntelliJ, and I'm even using them at 12pt. However, I think (for me) the issue isn't so much the top of the glyphs, but rather the fact that the bottoms of them are extremely similar. Just adding my two cents.

**Comment by chrissimpkins** [comment]
@bkromhout Brenden, come join us in #43 where the `i` vs. `l` issue is being addressed.  We are in the process of defining an approach to usability issues and tooling up to both analyze and make decisions about them.  This aspect of the project is being overseen by @burodepeper and we will have much more news soon (as well as a fix based upon these efforts!).  We are heading in a direction to make these issues much more objective in nature, and focused on a specific set of well-defined optimization target variables.  This will help us (and you) determine whether we hit the mark on changes that address usability concerns.  

Your ongoing feedback will be very helpful as we address these issues. Thanks much!

**Comment by burodepeper** [comment]
Hi @chris0e3, as @chrissimpkins mentioned, I'm overseeing these issues. If you would come over to #43 and read my latest comment on how you can help me, that would be great.
