### ISSUE TITLE
Space char width incorrect

### ISSUE THREAD

**Issue by jublo** [chrissimpkins/Hack#112]
The width of the space character seems to be incorrect.
Seen this in OTF, tested with [code.visualstudio.com](http://code.visualstudio.com).

I selected 4 space characters:
![image](https://cloud.githubusercontent.com/assets/6348321/10044684/2a266752-61fd-11e5-8f72-bc30c32932bb.png)

**Comment by chrissimpkins** [comment]
Platform and Hack build version?

I can confirm that the dimensions of the width of the space match the em size for the glyphs in the rest of the regular set for the OTF build as of the current release (v2.013).   Is this the version that you are using?  

Is it possible to turn on space highlighting in that editor so that we can see the tab/space positions?

**Comment by jublo** [comment]
OS X, running Version 2.010. What's the latest OTF build?

**Comment by jublo** [comment]
It *is* turned on. After upgrading to 2.013, things look beautiful, like this:

<img width="335" alt="bildschirmfoto 2015-09-23 um 16 19 25" src="https://cloud.githubusercontent.com/assets/6348321/10047532/f368f678-620e-11e5-87ff-f2c14bdf4534.png">

**Comment by jublo** [comment]
Wouldn’t have thought that the font is under *so* heavy development… :grinning:

**Comment by chrissimpkins** [comment]
mind trying the new 2.014 test build?   vertical metrics changing.  should not affect space chars but worth a check in your editor / platform combo.  currently ttf only.  If you prefer the otf files we can check when available.

**Comment by jublo** [comment]
Sure—it’s not a thing installing the TTF. Will keep you posted.

**Comment by jublo** [comment]
See here:

<img width="418" alt="bildschirmfoto 2015-09-23 um 16 28 02" src="https://cloud.githubusercontent.com/assets/6348321/10047792/1a8a4512-6210-11e5-9f3f-a13b2e30e54a.png">

**Comment by chrissimpkins** [comment]
Seems ok to me.  You?

> Wouldn’t have thought that the font is under so heavy development

Much more to come so that it is truly tailored to source code needs... Feel free to pitch in anywhere that you see issues.  It's great to get feedback in different platform/editor/bodies of code combinations.  This has led to a string of changes in recent weeks.  Currently working on hinting optimizations, better Powerline glyph alignments, and a new build chain.  

Enjoy!
