### ISSUE TITLE
Source code typeface web application to compare Hack with other commonly used faces

### ISSUE THREAD

**Issue by chrissimpkins** [chrissimpkins/Hack#116]
Work on this is in progress.  If you'd like to contribute, please let me know.  For those who would like to use it, we will post with additional details in this issue report thread when available.

**Comment by chrissimpkins** [comment]
This is now available at:

http://sourcefoundry.org/hack/playground.html

Please let me know if you have any problems with it.

**Comment by chrissimpkins** [comment]
Work underway to expand monospaced typeface support in the application.

**Comment by llimllib** [comment]
It would be awesome to be able to see two fonts side-by-side. Without that feature, it's pretty difficult to compare.

Sorry for just lobbing a feature request over the wall! I think this project is super neat, and feel free to ignore me.

**Comment by chrissimpkins** [comment]
We wouldn't ignore you!  This input is good.  @jublo designed the font comparison site.  Let's see what he thinks.  I guess my only concern with this is that we want to have sufficient room on the screen for users to visualize enough code to be informative.  Maybe we could have a way to go full screen with two code viewers for those who want to see side by side comparisons.

**Comment by jublo** [comment]
@llimllib Thank you very much for your constructive input!  I agree with you and Chris that comparing fonts could be a handy feature, and I think going full-screen in a side-by-side view might be a good solution to this.  (Either horizontal, or vertical, or ideally with a switcher.)

Do you think this could work?

**Comment by llimllib** [comment]
I think that would be awesome; any way you can see the two fonts side-by-side would help.

**Comment by chrissimpkins** [comment]
@llimllib This feature is now available on the Font Playground at https://sourcefoundry.org/hack/playground.html

Click the compare side-by-side button in the top right corner to access the feature.

Kudos to @jublo for the development effort and @burodepeper for input that led to the current design.   Let us know if you have any feedback once you give it a try.

**Comment by llimllib** [comment]
That's great! You all rock.

I've been using hack for the last two weeks, and couldn't be happier.

**Comment by chrissimpkins** [comment]
@llimllib We love to hear comments like that Bill.  I'm really glad that it is working for you.  Stay tuned.  We have a number of improvements in the pipeline and will be interested in your feedback.

**Comment by veeven** [comment]
How about a flip-flopping between two typefaces? For when side-by-side comparison isn't enough. Here is [something quick](http://webcraft.veeven.com/zmisc/flip-flop/) I've put together. This way, finer things can be observed and appreciated.

**Comment by jublo** [comment]
@veeven I can think of two ways to set this up:

Either flip-flop one of the comparison editors, while leaving the other,
or swapping the fonts selected for both editors.

What do you think?

**Comment by chrissimpkins** [comment]
@veeven Must admit I am a flip-flopping fan.  I like that approach.  @jublo would it be possible to just put a toggle button on the right sided editor so that you can toggle back and forth with the left sided typeface setting?  It's interesting to see the different attributes of the faces that become apparent with each of these comparison approaches (vertical, horizontal, toggled).

Yet another useful approach (different but complementary) would be the visual diff tool where users could see string overlays in two different faces.  This will show shape and spacing differences simultaneously if users would like to take it to that extreme.

**Comment by jublo** [comment]
> would it be possible to just put a toggle button on the right sided editor so that you can toggle back and forth?
@chrissimpkins Yes, it would.

**Comment by chrissimpkins** [comment]
@jublo Let's see what @veeven thinks, but my thought is that you don't need to go the extreme of swapping editor windows or changing font settings in both editors.  The same information should be gained with a single toggle switch in one of the comparison editors and I suspect that this would be a simpler approach from a development standpoint.

**Comment by jublo** [comment]
@chrissimpkins @veeven
Please take a look at http://sf-playground.github.io/sforg/hack/playground.html.

![](https://cloud.githubusercontent.com/assets/6348321/10768693/a941f6c8-7ce2-11e5-8447-a7d0019f2c63.png)

**Comment by chrissimpkins** [comment]
Merged to production site.  @veeven let us know what you think.

**Comment by veeven** [comment]
@jublo @chrissimpkins 
It's good. However, I found change happening two windows is distracting. I prefer single window for flip-flopping.

Thinking more about the design of the page itself, an alternative approach seems better. Basic idea is have a big editor area and a right side panel of options. Something like below:

```
[Language ▾] [Syntax Highlighting ▾]
[Size ▾] [Line Height ▾]

Typefaces:               [⇆]
Hack                    ⓘ ➕
Anonymous Pro           ⓘ ➕
Source Code Pro         ⓘ ➕
```

The only difference is that typefaces are listed out for direct selection, instead of choosing from a dropdown (which is obscuring the editor and making the change less obvious). I think this is more convenient than choosing from a dropdown. The behavior is as follows:

* Flip-flopping can be done by clicking `⇆` icon (we need a nice icon), It toggles between current typeface in the main editor with the last choice.
  * This icon gets enabled when user has selected one other typeface (than what's selected on load by the page).
* Clicking on the typeface in the list applies that typeface to the editor.
* Clicking ⓘ shows the information popup about the typeface. (Alternatively, we can just make it a link and icon and point it to the more info url.)
* Clicking + icon adds an editor with this typeface, beside the first editor.
  * Depending on the screen size and text in the editor, the new editors can either be added to the right side or below.)
  * Additionally, we can be smart about the placement of the second (and subsequent) editors. Instead of splitting the available space equally, we can just overlap the second one such that it just does not cover the text in the main editor.
  * The overlapped editors can be dragged horizontally (for sideways) or vertically. (Overkill? Probably!)
  * Once an editor is added, the + icon on the typeface row becomes ✖. And/or, second and subsequent editors will have close on top right..

Though this sounds a bit more complex, I think it simplifies the playground. What do you guys say?

**Comment by burodepeper** [comment]
First of all, @veeven, thanks for your input.

I think the tool is more than sufficient for the time being. We already have the intention to redesign the tool from the ground up. Besides that, it isn't part of our current primary focus, so 'good enough' really is 'good enough' at the moment. At least, that's my opinion.

As for the future:
There are various scenarios in which a user would use this tool, and from a design perspective, they are pretty diverse. We'll keep them in mind for the next iteration. I really appreciate your input @veveen, and when the time is ripe I hope you'll supply us with additional productive feedback. If you are really dedicated (and got some design skills), you're welcome to pitch in as far as I'm concerned.
