### ISSUE TITLE
Side by side comparisons of fonts (website)

### ISSUE THREAD

**Issue by chrissimpkins** [chrissimpkins/Hack#131]
update the Font Playground to include a full page side by side  comparison of Hack vs other typefaces

**Comment by jublo** [comment]
http://sf-playground.github.io/sforg/hack/playground.html

![](https://cloud.githubusercontent.com/assets/6348321/10669044/3f73dce0-78df-11e5-931e-6f9ebaeb44ab.png)

**Comment by burodepeper** [comment]
Nice!

A few comments:
- vertically separate them by default (the switch function wasn't clear to me btw)
- align the selector for typeface with the code-frame
- Hack at 12 (what unit?) in the browser renders _a lot_ bigger than 12px in my text editor (zoom is at 100%)
- The default line-height (of 1?) is different than the line-height of 1 in my editor.

**Comment by jublo** [comment]
> align the selector for typeface with the code-frame
@burodepeper Please explain.

**Comment by jublo** [comment]
> the switch function wasn't clear to me

Please make a suggestion how to make it clearer. Use a different icon? Show an unobtrusive popover on first open?

**Comment by jublo** [comment]
> - vertically separate them by default
> - Hack at 12 (what unit?) in the browser renders a lot bigger
> - The default line-height (of 1?) is different

Should be fixed. Please confirm and/or comment.

**Comment by burodepeper** [comment]
![schermafbeelding 2015-10-22 om 19 01 51](https://cloud.githubusercontent.com/assets/3703530/10672305/636ddb4a-78ef-11e5-9d10-ceffde8e1a3c.png)

This is just a quick sketch, perhaps you have a better idea.

- I've moved the dropdown-buttons around.
- I've changed the default labels to indicate what they are, rather than their value. Also, I've made them grey, to make them slightly less important.
- My icon suggestion for switching between horizontal and vertical is ugly, but I think you get the idea.

In general, if I'd take my time designing this, I'd have the interface to switch between typefaces (etc) be less dominant, compared to the two editors. They are rather harsh in their contrast. But that's not the most important thing at this point.

I have to say that editing in two editors at the same time is a good addition, although I'm still sticking with Hack ; ) Oh, another idea, set the typeface of the second editor by default to something other than Hack, preferable something with the same line-height, but a significantly other identity. @chrissimpkins might know which one would be best suited here.

**Comment by burodepeper** [comment]
Type-size and line-height are good now!

**Comment by jublo** [comment]
@chrissimpkins @burodepeper Here is a new iteration of the font playground side-by-side comparison; looking forward to your feedback.

http://sf-playground.github.io/sforg/hack/playground.html

Changed in this iteration:

- Use Source Code Pro as default font face for editor 2 (right/bottom)
- Enhance buttons for vertical/horizontal alignment
- Change default labels to indicate what they are, rather than their value, except for the font face
- Re-position editor controls (avoiding large mouse moves when selecting font faces)
- Make them less prominent (half-transparent background, less contrast in text color)

Fixed:

- Update font info text and link only when first editor font face is changed

Notes:

- The editor controls (drop-down selects) and the first editor are shared between the normal and the comparison view; just their appearance changes using CSS.
- To change the default font for the second editor, move the `data-selected-editor2` attribute to a different `<option>` of the font face select.

Preview:

![](https://cloud.githubusercontent.com/assets/6348321/10710499/b1380d86-7a5d-11e5-9ab9-1de2d5d9c7cc.png)

**Comment by chrissimpkins** [comment]
@jublo Looks great JM.  I really like the design that you and David landed on.  The only issue that I see is that the size, language, syntax highlighting defaults do not show up on the initial page load and they don't appear to change/display when you make changes in the dropdowns. 

Let's see what David has to say.

**Comment by chrissimpkins** [comment]
Here is what I am seeing with a size and highlighting change:

![playground](https://cloud.githubusercontent.com/assets/4249591/10710567/12071b32-7a2e-11e5-90ef-e5cee7643553.png)

**Comment by burodepeper** [comment]
Looks better to me now (only done a quick scan). As I've said in Slack, I think the web-app in itself needs some rethinking, but for now, it is better than good enough.

@jublo What do you think of the changes yourself? Do you agree with them?

**Comment by jublo** [comment]
Yes, I agree with them.  Let’s note that there is room for improvement, but I assume this will best serve many users in its current state (including mobile ones, since I coded it responsively).

**Comment by burodepeper** [comment]
Ok, let's publish the beast then, unless there are crossbrowser quirks.

**Comment by jublo** [comment]
Running a cross browser scan now.

**Comment by jublo** [comment]
@chrissimpkins Good to go, works fine in all browsers, except for IE9 and below.

@burodepeper also provided a better default sample code, see a preview here: http://sf-playground.github.io/sforg/hack/playground.html

**Comment by chrissimpkins** [comment]
:+1: merging today

**Comment by jublo** [comment]
@chrissimpkins Should be closed.

**Comment by chrissimpkins** [comment]
@jublo thanks
