### ISSUE TITLE
Backslash in italics is too close to vertical

### ISSUE THREAD

**Issue by alerque** [chrissimpkins/Hack#154]
Several times now I've run into situations with the backslash (`\`) the italic variant that that have been visually ambiguous. The slanted version is just _too_ slanted. It needs to be closer to a backslash with a minor variation on the angle than it is to a pipe (`|`). I had to swap out characters in my document a couple times to confirm that I had the right symbol—something I've never run into before with other fonts.

![selection_077](https://cloud.githubusercontent.com/assets/173595/11037962/550d8ca8-8709-11e5-80d5-d3459f4d019b.png)

In reference to #142, I would even argue that if so many of the other symbols (including the forward slash) aren't morphing at all, the backslash would also be a candidate for this. On the other hand if it does get a minor shape adjustment it should be consistent across other symbols as well including the other slash direction and the pipe. And it should be subtler than it is now.

**Comment by chrissimpkins** [comment]
Thanks Caleb.   Are you using a syntax highlighter that only obliques the puncutation glyphs?  In that image the alphabetic glyphs on the same line look like they are from the regular set

**Comment by burodepeper** [comment]
I agree with you, the backslash isn't distinguishable enough.

On a side note, what editor and syntax-theme are you using, and in what programming language is that piece of code written? In my design opinion, source code elements where punctuation matters should _never_ be italicized. I'm curious how blasphemous your combination of editor, theme, etc. is on this issue.

**Comment by chrissimpkins** [comment]
@burodepeper use case analysis?

**Comment by burodepeper** [comment]
Yup.

**Comment by chrissimpkins** [comment]
@burodepeper :+1:

**Comment by alerque** [comment]
The editor is NeoVim. Nothing blasphemous about that! But after that things get sketchy. The language being displayed is the [SILE Typesetter](https://github.com/simoncozens/sile)'s markup language. The vim syntax highlighter for that language is something I've only just started [hacking on](https://github.com/alerque/vim-sile), but I've started from the LaTeX highlighter as a template and that does indeed italicize some symbols, specifically backslash escaped symbols. Hence the backslashes and braces in `\begin{verbatim}` are not italicized while the ones in `\\begin\{document\}` are. If you want to call this highlighting behavior blasphemous I might agree with you, but I'm fairly used it from long hours editing TeX files. It's not an uncommon behavior and numb-scull highlighters shouldn't be an excuse for not making the most legible font possible.

**Comment by burodepeper** [comment]
Thank you for the details.

About the blasphemous part; that's also a bit a sketchy area, and part of it is because I like using the word blasphemous ; ) The sketchy part has to do with certain characters (in source code typefaces) not being italicized at all. The reason for that is most likely because their 'natural' shape has so significant meaning, that you don't want to change that. Think of a slanted `|`. Your use-case is an interesting point of view, because it highlights weak areas of Hack that we haven't considered yet. In myself as a use-case, I think I only run into backslashes when escaping things in regexes or in `\n`s.

Would you mind sending me some source code screenshots (of anything really) that reflect your use-case for me to attempt to look at things through your eyes?

**Comment by chrissimpkins** [comment]
@caleb I'm in agreement with those comments.  We are in the process of formalizing this type of change proposal and this will involve consideration of associated effects in other languages that we have defined as our targets for development.  This is all very early stage work.  Will step back and let @burodepeper expand as he is overseeing the usability analyses.  Much more news as this matures.

**Comment by schorsch3000** [comment]
Today i ran into the same problem, using hack as the font in intellij a italic backslash looks almost like a normal pipe. the only difference is: the pipe is taller.

**Comment by chrissimpkins** [comment]
Work is in progress on this issue.  Will post here when we have something to try.

**Comment by chrissimpkins** [comment]
Adding this to the v2.020 release

**Comment by chrissimpkins** [comment]
@burodepeper Thoughts?  I am prepared to start work on this.  My inclination is to move away from oblique punctuation altogether but would like to see what you have in mind.

**Comment by burodepeper** [comment]
Hello all,

I've been discussing this issue with @chrissimpkins once again, and we've decided to pick it up for the upcoming release. We have been discussing, quite extensively, how the italics relate to the regular set. It is my opinion that the literal issue as posted by @alerque is not the actual issue. Or at least, it is not an issue with Hack, but rather with poor syntax highlighting. For the sake of brevity, I won't go into too much detail on that.

I do however acknowledge that the italicized pipe and regular backslash are similar, and since they are both part of ascii, there should be a good enough visual distinction between the two of them. I suggest we try gently breaking the pipe (as is not too uncommon) to see how that affects the general feel. I believe @chrissimpkins will have a demo screenshot of that before not too long.

The reasoning behind what's mentioned above is primarily based on the idea that the characters from the regular and italics sets live in separate contexts (almost as if they are different typefaces altogether). When you are reading source code, you don't want to have to question within which of the two contexts you have to interpret the shape of a glyph. Mixing regular with italics side-by-side creates this confusion however. This is simply not something that can be fixed (by us). Our aim is to provide good visual distinction within the glyph's direct context (either regular or italics). How that tool is implemented by whatever code-editor/syntax-highlighter you use is out of our hands unfortunately. I do have a strong opinion on what to do and what to avoid if anyone's interested in it.

**Comment by chrissimpkins** [comment]
@alerque 
@schorsch3000
@burodepeper 

New test builds include a break in the italic set pipe glyph to address this issue.  Please let me know what you think and whether you feel that this adequately addresses this concern.

The builds will show as v2.020; DEV-03062016 and are available here:

https://github.com/chrissimpkins/Hack/tree/development/build/test_builds/DEV03062016

I haven't included this change in the bold italic set yet.  Have a look in the regular vs. italic set for now if you will and I will include these changes in the bold vs. bold italic sets if this seems adequate.

**Comment by chrissimpkins** [comment]
The hints will need a bit of attention so give this a shot at multiple sizes to view the divided pipe rendering.  At some sizes, the space between the strokes is lost.  I will correct this if we are happy with this change.

![pipe](https://cloud.githubusercontent.com/assets/4249591/13560035/ccfddb50-e3e8-11e5-8f90-e726289bcfef.gif)

**Comment by burodepeper** [comment]
@chrissimpkins Did you make the italic pipe intentionally not slanted? I believe that both the regular and italic pipes should be broken, with the italic pipe also being slanted. The size of the gap at 13px is great btw.

**Comment by chrissimpkins** [comment]
it has never been slanted in the set.  any slanting is coming from the renderer not the design.  This is probably why it looks so similar to the backslash.

**Comment by chrissimpkins** [comment]
@burodepeper why in the regular set? this is not a problem there.

**Comment by burodepeper** [comment]
For consistency.

And for the sake of consistency, didn't we already come to an unconfirmed agreement that all characters in the italics set should be slanted, as that is what defines them as italic? Remember our discussion on Slack about this. It is not the actual shape that would be slanted (so no distorted periods), but rather the conceptual shape of the character that is drawn on a particular angle. Having an up-right pipe in the italics set goes against this very basic principle. If you can assume (as a user) that all characters have that same slant, then the awareness of being within that slanted context is almost enough to make a clear distinction between the two slashes and the pipe. Breaking the pipe is added to further distinguish its shape from the slashes, in both regular and italics sets.

**Comment by chrissimpkins** [comment]
@burodepeper let’s address the more broad issue across the entire italic and bold italic sets in this new issue report: #186 . The punctuation glyphs in these sets definitely deserve a bit of attention and I agree with many of the changes that you mentioned above/that we’ve discussed in the past.

As for the break in the pipe glyph, this is largely an issue that will exist outside of source code text because it is in the italic set.  The typesetting markup issue here is somewhat of an edge case scenario and not one for which the fonts are primarily designed.  Most users will see these changes in code comments and string literals.

I see two problems with the introduction of the broken pipe glyph in the regular and bold sets:

1. This change then turns into something that will be common in source code text as this glyph is commonly used as an operator.  Users are not used to seeing a broken line as their pipe character and I do not find this change to be one that improves upon the aesthetics or legibility of the glyph shape.  It is a fairly dramatic visual change to address the issue of similar slants that only exist in the italic and bold italic sets.

2. There is already a Unicode definition for a shape that is the same as this new design  (U+00A6 - broken bar).  The change here creates a shape that cannot be visually distinguished from this existing Unicode character and I think that we should avoid the introduction of a new problem in the target use case area to address an issue in an edge case.

 This is an attempt to address a problem in the oblique sets that does not exist in the regular or bold sets and my recommendation would be to avoid the introduction of this change in the regular and bold sets, particularly if this is only in the name of design consistency.

I am certainly open to other thoughts.  Those are my 2 cents.  Let’s continue to discuss this and see where we wind up.

**Comment by burodepeper** [comment]
Okay @chrissimpkins, for practical reasons, let's go with your two cents for now.

I have one additional remark though (as illustrated by the following screenshot): why is the backslash slanted in italics, but the forward slash not?

![schermafbeelding 2016-03-15 om 14 55 28](https://cloud.githubusercontent.com/assets/3703530/13780045/0d4ed55c-eabe-11e5-8ec2-733f9d65a09c.png)

**Comment by chrissimpkins** [comment]
@burodepeper 

I would need to look back through the changelog to confirm, but I don’t believe that I modified any slants in these ASCII punctuation glyphs from the original slants that were included in the Bitstream Vera Sans Mono set.  This is definitely something that we can and should discuss.  Let’s use #186 or a new issue report to address it.

**Comment by chrissimpkins** [comment]
Are there any other comments here about the design choice for the broken pipe glyph in the italic set or are we good to go with this change?  If we are set on this modification, I will include this in the bold italic set and start work on the hints so that it renders properly at all target text sizes.

**Comment by burodepeper** [comment]
@chrissimpkins I think what is most confusing about the slanted backslash in comparison to the forward slash is that it has become shorter in length. Slashes in general stand out from other characters because they are larger. I don't think we should create a new issue for this. In my opinion, the backslash in the italics set should be replaced by the regular backslash. That seems consistent, and while I still like the broken pipe (I actually prefer it over the non-broken version, also for the regular set), it also makes the broken pipe technically unnecessary. To conclude: broken pipe is good, can also be applied to bold italic; backslash in italic to be replaced by unslanted version.

**Comment by chrissimpkins** [comment]
@burodepeper are you seeing this shortening across a range of sizes?

**Comment by burodepeper** [comment]
@chrissimpkins If two lines (of the same height) are slanted at a different angle, then by definition they are different in length. That's just simple math. If you want proof, perhaps I should cc @pythagoras ;) It is not a hinting issue, if you were wondering that.

**Comment by chrissimpkins** [comment]
@burodepeper The image that you posted appeared to show a pixel clipped from the top and bottom of the glyph, but you are correct they appear to be the same height.

<img width="491" alt="slashes" src="https://cloud.githubusercontent.com/assets/4249591/13791407/57309156-eac3-11e5-9f02-f50f9ef5b897.png”>

Agree with the changes that you proposed and will implement these are part of v2.020.  I will try to work on these this week.

**Comment by chrissimpkins** [comment]
<img width="491" alt="slashes" src="https://cloud.githubusercontent.com/assets/4249591/13791407/57309156-eac3-11e5-9f02-f50f9ef5b897.png”>

Agree with the changes that you proposed and will implement these are part of v2.020.  I will try to work on these this week.

**Comment by chrissimpkins** [comment]
@burodepeper The image that you posted appeared to show a pixel clipped from the top and bottom of the glyph, but you are correct they appear to be the same height.

<img width="491" alt="slashes" src="https://cloud.githubusercontent.com/assets/4249591/13791580/354af544-eac4-11e5-8533-70c4f8ca1126.png">

Agree with your proposed changes and will include these in the v2.020 release.  I will try to work on these glyphs this week.

**Comment by chrissimpkins** [comment]
All fixes discussed here to date for the italic and bold italic sets are now available as Version 2.020;DEV-03162016 in this directory:

https://github.com/chrissimpkins/Hack/tree/development/build/test_builds/DEV03162016

I updated the hints for both sets across 6 - 14 ppem so that the bar glyphs maintain the space within the stroke at all of these sizes.

Let me know what you think.

**Comment by chrissimpkins** [comment]
Here is where we are with the glyphs in the italic set:

![pipe-italic](https://cloud.githubusercontent.com/assets/4249591/13834188/4f84ce3a-ebc3-11e5-886a-e62fc2e3352b.png)

![fslash-italic](https://cloud.githubusercontent.com/assets/4249591/13834465/b2610a80-ebc5-11e5-9221-022e20475bdd.png)

![bslash-italic](https://cloud.githubusercontent.com/assets/4249591/13834193/57bc123e-ebc3-11e5-98a0-b3c5f0721815.png)

**Comment by burodepeper** [comment]
@chrissimpkins On the road today, I'll check them out as soon as I get home.

**Comment by chrissimpkins** [comment]
@burodepeper no rush. thanks David.

**Comment by burodepeper** [comment]
@chrissimpkins Did a quick test, and everything looks fine to me at 13px. Since it's a copy-paste between sets, I think it is safe to assume that it looks fine across all sizes?

**Comment by chrissimpkins** [comment]
> I think it is safe to assume that it looks fine across all sizes?

@burodepeper : The new break in the pipe glyph looks good in `ftview` at 8 - 14ppem after the new hints were applied (italic / bold italic sets).  Assuming that there is no additional feedback here, we will release these changes in v2.020.

**Comment by chrissimpkins** [comment]
These fixes were included in the v2.020 release which is now available.  Thanks to all for the help here.
