### ISSUE TITLE
variant of the font with hand written 'a'

### ISSUE THREAD

**Issue by mathieujobin** [chrissimpkins/Hack#157]
I love your font. its great. but I dont understand why most computer fonts use this strange 'a' I never ever wrote with a pen. my 5 years old things it looks like a 6. I'd love to see variants of fonts with a like we write with a pencil.

see the 972 console font for an example

http://alexandre.deverteuil.net/pages/consolefonts/#972.cp%2816%29

thanks

**Comment by burodepeper** [comment]
Hi @mathieujobin,

The handwritten `a` could be confused for an `o`, because it's just the little stem at the bottom right corner that distinguishes the two of them. If you translate that to a source code typeface at `11pt`, that distinction becomes a mere single pixel. In an environment where typos are a serious issue, it is better to use safe, distinguishable shapes, especially for characters within the ascii character set. That is also the reason why the `0` often has some sort of marking in it, so it doesn't get confused with an `O`.

On our "dreams for the future" list, we do however have a tool that could add a handwritten `a` to your custom version of the typeface, but I can't make any promises just yet.

I hope this at least explain things a little bit.

**Comment by mathieujobin** [comment]
I understand, thanks for the explanation. hopefully your dream will become true.

I still hope to see more fonts getting closer to what we write on paper

**Comment by burodepeper** [comment]
@mathieujobin You could always create the appropriate glyph yourself.

**Comment by mathieujobin** [comment]
if I knew how.
i have no idea what type of skills this requires

**Comment by burodepeper** [comment]
Take a look at www.glyphsapp.com
That's the primary app we use for the design of glyphs. Just open up the `ttf` files from Hack (or any other typeface), and move some stuff around. It is somewhat similar to Adobe Illustrator. There's something about licenses and stuff, but for personal use, I'm sure everybody will look the other way.

**Comment by chrissimpkins** [comment]
FontForge is a libre alternative
