### ISSUE TITLE
Programming ligatures

### ISSUE THREAD

**Issue by antanst** [chrissimpkins/Hack#166]
Since this typeface is marketed towards programming, perhaps some ligatures would be of interest, like in the Fira Code, Hasklig or PragmataPro fonts. Personally, I find Fira Code's ligature preferences the most correctly designed and pleasing to the eye.

**Comment by chrissimpkins** [comment]
Thanks for the suggestion Antonis. We have an open issue report and a lot of backstory/opinions about this issue.  It is possible that this will take place but it will likely be in the form of a new set of fonts rather than in the primary font for the issues that I laid out there.

Feel free to join the conversation in #35

**Comment by jsejcksn** [comment]
@chrissimpkins Suggestion: #35 adopts the title of this issue for greater indexability. I found this one first in searching.
