### ISSUE TITLE
Thin vertical line of different color at the edge of filled triangles

### ISSUE THREAD

**Issue by jceb** [chrissimpkins/Hack#184]
Hi, thank you for the great font!

I found a small rendering issue with the characters  (U+E0B2) and  (U+E0B0) that I use for my vim status line.  There is a thin vertical line at the left/right edge of the character that is rendered in a different color.  I found the line to be there with every font size between 10 and 32.  I did my tests on Linux with the terminals Konsole and st, the latest stable version 2.019 of Hack and I also tried the latest development build (a17f5b0b7a6a3248a8e44fa7a3ae2a5cf4d47080).  The screenshot was taken with st and the development build.  Autohinting and antialiasing were disabled but I get the same results when options are turned on.
![render_issue](https://cloud.githubusercontent.com/assets/101593/13548696/6504adfa-e2f6-11e5-9bf6-262b21834dea.png)

**Comment by chrissimpkins** [comment]
Thanks much for the detailed report Jan.  The information is tremendously helpful.   This looks like an antialiasing issue.

You can see the problem is similar for the left facing arrowheads in white and blue:

<img width="475" alt="anti1" src="https://cloud.githubusercontent.com/assets/4249591/13555447/aa1b14d6-e38e-11e5-9b4f-8c35ce2c5bc1.png">

<img width="302" alt="anti2" src="https://cloud.githubusercontent.com/assets/4249591/13555449/b0c188c4-e38e-11e5-8066-1d1a28d84da3.png">

and occurs in the right facing arrowhead but in a different color (blue):

<img width="557" alt="anti3" src="https://cloud.githubusercontent.com/assets/4249591/13555455/c8b619fe-e38e-11e5-8ee0-573db74b70f5.png">

If you have a close look at the vertical lines of other glyph shapes, you can see similar shading along their margins:

<img width="371" alt="anti4" src="https://cloud.githubusercontent.com/assets/4249591/13555457/f1aba9a0-e38e-11e5-95ae-d92531aeca7a.png">

How are you modifying your antialiasing settings in the editor?

**Comment by jceb** [comment]
For st, I recompiled the terminal and started it again but it had no effect.  I tried it with the xfce4-terminal and adjusted antialiasing in the window manager's settings and it worked better.  Here is the screenshot with antialiasing enabled, the vertical line can be spotted easily:
![with_antialiasing](https://cloud.githubusercontent.com/assets/101593/13559844/9d3a49fa-e418-11e5-8888-8bb6efc57985.png)

And here's the same window with antialiasing disabled:
![without_antialiasing](https://cloud.githubusercontent.com/assets/101593/13559851/b0f097e2-e418-11e5-8972-54a7871cecd5.png)

I'm not sure how it works with fonts but is there anything that can be done to prevent antialiasing from rendering this column?  Turning antialiasing completely off is no option, I guess ;-)

**Comment by chrissimpkins** [comment]
I agree that you want the antialiasing.  The pixellated artifacts on angled lines and curves is very apparent in the UI without it.  I’m not aware of an approach that permits you to selectively antialias glyphs (or portions of glyphs).  Leave this open and see if anyone else has suggestions?
