### ISSUE TITLE
Esperanto support

### ISSUE THREAD

**Issue by cdlm** [chrissimpkins/Hack#21]
Esperanto needs just a dozen letters with diacritics: ĉĈĝĜĥĤĵĴŝŜŭŬ (that's `cC gG hH jJ sS` with circumflex, and `uU` with breve)

**Comment by chrissimpkins** [comment]
Will add these and get a version out to you to have a look at.  Hopefully later this week.  Thanks much for the suggestion!

**Comment by chrissimpkins** [comment]
Unicode reference for the development of this set:

Unicode table for Esperanto character set 

http://unicode-table.com/en/sets/esperanto/

**Comment by chrissimpkins** [comment]
Can you let me know what platform you are on?  I am going to prepare some testing builds with these glyphs.

**Comment by cdlm** [comment]
I'm on OS X 10.10.5.

**Comment by chrissimpkins** [comment]
thanks. will let you know when a version is ready to try

**Comment by chrissimpkins** [comment]
Queued for next release

**Comment by chrissimpkins** [comment]
@cdlm Damien, do you mind having a look at the images in PR #118 to see if the positions of the diacritic marks look appropriate on all of these glyphs?  We will create a test build that you can try before we release this if you are available/willing to help us test them.  It would be helpful to have feedback from someone who uses the characters.

**Comment by chrissimpkins** [comment]
From @cdlm : 



First of all, uppercase and lowercase are used as you'd expect in english. However, the accented letters are distinct and sorted just after their non-accented variant in the alphabet. There is no q, w, x, or y. Letters are always pronounced the same (the accented ones are different letters, so they have a different sound, even though it's related to the non-accented one. I can't say for sure, but I doubt there is any word with two adjacent diacritics…

Ĥ and Û are the rarest ones. Ĥ is the greek khi / spanish jota / german hard H as in Bach or in LaTeX; my dictionary has half a page of words starting with Ĥ, and words which originally used it are now orthographied with k instead, wikipedia has a nice explanation and examples.

eĥo (echo), ĥaoso (chaos), Liĥtenŝtejno (Liechtenstein), mariĥuano :)

Ŭ corresponds to english W… my dictionary has only five entries starting with Ŭ, most of them onomatopoeia or transliterations (ŭato means watt, but can also be written vatto). Otherwise, I've only seen used after A or E, as part of a diphtong.

Ŭaŝingtono (Washington, but Vaŝingtono is also used)
Eŭropo (Europe)
eŭfemismo (euphemism)
Aŭgusto (August)
ĉirkaŭ (around)
antaŭ (before)
antaŭulo (ascendant)
antaŭen (forward)
antaŭeniĝi (to progress)

Ĵ sounds like french J
Ĵuraso
ĵeti (to throw)
ĵurnalo (journal)
belaĵo (a beauty)

Ĝ sounds like english J
ĝi (it, this)
ĝenro (gender)
grandiĝi (to grow, become taller)
manĝi (to eat)
averaĝo (average)

Ĉ sounds like tsh
ĉu ne? (isn't it?)
ĉio (this thing)
aĉeti (to buy)
ĉeno (chain)
ĉefinĝeniero (chief engineer)

Ŝ sounds like sh
ŝi (she)
artiŝoko (artichoke)
ŝovi (to push, to make sth slide)
ŝelako (shellac)
ŝnuro (rope)

I'm still a beginner at the language so I still need to cheat using dictionaries and google translate to find my vocabulary. Maybe grepping through a word list would find more interesting examples…

**Comment by chrissimpkins** [comment]
From @schierlm: 

FTR: There are Esperanto words with two adjacent diacritics. In most cases either the first one is ŭ part of an aŭ or eŭ diphtong (for example antaŭĝoji [to eagerly anticipate] or kaŭĉuko [rubber] or it is a compound word like the (old-fashioned) vojaĝĉeko [traveller's cheque].

And of course, for testing, the (in)famous Eĥoŝanĝo ĉiuĵaŭde [echo change every Thursday] should not be missing (although it does not contain any adjacent diacritics), which is nonsense, but not more nonsense than brown foxes jumping over lazy dogs :)

**Comment by chrissimpkins** [comment]
@cdlm @schierlm @jublo 

Some very minor horizontal positioning changes to the diacritic marks on the glyphs that @jublo made in the regular set.  Here is a specimen sheet based upon suggestions in the above comments:

### Large Text Size
<img width="703" alt="esperanto-rev-1_large" src="https://cloud.githubusercontent.com/assets/4249591/10327414/ff754686-6c74-11e5-8620-6b6e6cd2531f.png">

### Small Text Size
<img width="400" alt="esperanto-rev-1_small" src="https://cloud.githubusercontent.com/assets/4249591/10327416/0221ca58-6c75-11e5-9cd8-8326eabca473.png">

### Diacritic Marks Adjacent to Each Other
<img width="386" alt="esperanto-adjacent-diacritics" src="https://cloud.githubusercontent.com/assets/4249591/10327417/05047d9c-6c75-11e5-883f-0b314478faf8.png">

The circumflex mark above the `h` looks out of place to me compared with the other marks, but perhaps this is how it normally appears in text?  I don't know that it would look any better above the vertical stroke and would need to be pushed even higher in the box.  It looks like @jublo set it at the same level as the circumflex marks on the upper case letters:

<img width="264" alt="circumflex-compare" src="https://cloud.githubusercontent.com/assets/4249591/10327526/50a08894-6c76-11e5-899b-b9391e1e066a.png">

and when viewed in that context it seems to maintain the appearance of these marks.

If it looks like we are getting close with positioning on the diacritic marks, I will update the other three sets and merge this into the next release.  Thanks to all for your help and to @jublo for a beautiful new set of glyphs to address this issue.

@jublo: I pushed UFO source (generated with Glyphs from the ttf) that includes these changes, regular set only at this point.  It is in the issue branch in the `source/development/jublonet` directory.

**Comment by cdlm** [comment]
:+1:

**Comment by chrissimpkins** [comment]
@cdlm ty!

Will see if @schierlm has any thoughts today and then push ahead with these.

**Comment by schierlm** [comment]
Looks fine to me too :)

**Comment by chrissimpkins** [comment]
@schierlm great!  We will include these in the next release.  Hope to have it out in the next several days.  Will update here when there is a build available to try.

**Comment by chrissimpkins** [comment]
A new test build is available that includes the outstanding Esperanto glyphs that were recommended here.  Please let us know what you think.

[Hack-Regular.ttf](https://github.com/chrissimpkins/Hack/blob/development/build/test_builds/2_016/Hack-Regular.ttf?raw=true)
[Hack-Bold.ttf](https://github.com/chrissimpkins/Hack/blob/development/build/test_builds/2_016/Hack-Bold.ttf?raw=true)
[Hack-Italic.ttf](https://github.com/chrissimpkins/Hack/blob/development/build/test_builds/2_016/Hack-Italic.ttf?raw=true)
[Hack-BoldItalic.ttf](https://github.com/chrissimpkins/Hack/blob/development/build/test_builds/2_016/Hack-BoldItalic.ttf?raw=true)

**Comment by chrissimpkins** [comment]
These changes were included in the v2.017 release

**Comment by schierlm** [comment]
Am I the only one where the ŭ does not render in regular, but in Bold, Italic and in BoldItalic?

![screenshot](https://cloud.githubusercontent.com/assets/1568931/10947090/5b16ab7a-8326-11e5-9fc4-06019b285d77.png)

**Comment by burodepeper** [comment]
![schermafbeelding 2015-11-04 om 19 03 11](https://cloud.githubusercontent.com/assets/3703530/10947155/cd2f15f8-8326-11e5-806b-05ee6b653d38.png)
My ŭ looks different in shape to the other u's. Is it a fallback?

**Comment by chrissimpkins** [comment]
Will confirm this evening and push a new version if it is missing.

**Comment by cdlm** [comment]
Yup, Font Book shows ŭŬ as missing glyphs, and just for Hack Regular

**Comment by chrissimpkins** [comment]
pushing a new release this evening.  apologies!

**Comment by chrissimpkins** [comment]
new v2.018 release is now available that includes the U/u breve glyphs in the regular set.
