### ISSUE TITLE
Windows Installer Documentation

### ISSUE THREAD

**Issue by DungeonCaster** [chrissimpkins/Hack#222]
Your documentation for the executable Windows installer (and the download website page at http://sourcefoundry.org/hack/) should warn people that it requires a system reboot. Providing this information up front is just good manners for any Windows product.

**Comment by chrissimpkins** [comment]
Excellent point.  @texhex thoughts?

**Comment by texhex** [comment]
Well, I could add this information to the [Usage block](https://github.com/source-foundry/Hack-windows-installer#usage) in README. Would that be enough?

**Comment by chrissimpkins** [comment]
Let us know what you think @DungeonCaster

**Comment by DungeonCaster** [comment]
Hi @chrissimpkins and @texhex:  I think a simple sentence at the end of the Windows section in the README.md file is great. Something like this:

> To simplify the installation process on Windows systems, we've created the Hack Windows Installer which will guide you through the installation process. This installer addresses a number of common rendering issues that occur with font installs/updates on the Windows platform and is the recommended approach for Windows users. **Note: A reboot is required after running the installer.**

On the website you could add similar text to the paragraph above the Linux/Windows download buttons:

> For a quick installation, choose the option for your operating system below. This will download either an archive with TrueType (.ttf) fonts, or take you to the download site for a convenient setup application that will help install Hack on Windows systems (**a reboot is required after running the installer**).

The reason I **bolded** the sentence is because almost no font installs in Windows require a reboot anymore, In fact I'm not exactly sure why your installer does in this case since I can [install Hack using Choco](https://chocolatey.org/packages/hackfont) without rebooting (if you're not familiar with Choco, it is a Windows application very much like Linux's _apt-get_).

**Comment by texhex** [comment]
First off, sorry for the long delay. 

I have no problem adding a note to the Hack-Windows-Installer, but I would keep that detail out of the default Hack documentation. If someone ops-in for the installer, they will find the note there. 

And just to make sure: Our installer itself does not require a reboot, the installer can happily install the font in 99.9% of all cases without any reboot. We are requesting a reboot because a lot of applications do not react on WM_FONTCHANGE and Windows itself keeps the old font cached, so the new version is either not used or even not available for apps. That's why we issue an restart when there was a new file installed. 

See [FontInstallationIssues](https://github.com/source-foundry/Hack-windows-installer/blob/master/FontInstallationIssues.md) for more details.

**Comment by chrissimpkins** [comment]
Thanks @texhex!
