### ISSUE TITLE
Curly braces and dot do not align well vertically with others

### ISSUE THREAD

**Issue by nazar-pc** [chrissimpkins/Hack#223]
* PhpStorm (basically, any JetBrains IDE)
* Hack 2.020
* font size 11
* line spacing 1.2
* Linux

![2016-08-27 06-34-51](https://cloud.githubusercontent.com/assets/928965/18024934/82f9fece-6c20-11e6-800a-967986b167f1.png)

As you can see `()` and `[]` are on the same line, while `{}` are slightly higher.
The same with `.` - it is higher than `,`, `;` and `:` characters.

My primary font for years is DejaVu Sans Mono, I'm just evaluating Hack as potential replacement. Hack did very good progress since initial release, but looks like DejaVu is still slightly better.

**Comment by nazar-pc** [comment]
Just found #141, might be related (but this one is using different font size)

**Comment by chrissimpkins** [comment]
Much of this has been tooled to code.  Try posting images with blocks of your common code types and let's discuss in that context.   The goal is not necessarily orientation relative other similar glyphs but rather appearance and clarity in bodies of code text.

**Comment by nazar-pc** [comment]
It just seems odd when very similar characters have different positioning. If it is intentional - I'm closing this issue.

**Comment by chrissimpkins** [comment]
Sorry didn't mean to dissuade you.  I am not claiming that they are optimal, just wanted to explore in code with you.  If you are interested feel free to open it back up and post some shots of code with these glyphs.  We can take a look and see if there are things to optimize.

**Comment by nazar-pc** [comment]
So what are your thoughts on this? Is this something that should be fixed?

**Comment by chrissimpkins** [comment]
> Is this something that should be fixed

For the vertical orientation of the braces, likely yes.  Will definitely consider this change for a future release.

For the separated line in the vertical line glyph in the italic set (`|` U007c) this was an intentional design decision suggested by @burodepeper.  The rationale was that when a slant is added to a vertical symbol it can be confused with `/` UOO2f .  While we want the fonts to be aesthetically pleasing, the top priority has been code clarity in most of our recent design decisions.  Some decisions have been successes, some have been failures (see the closed cyrillic C issue report for an attempt at clarity that generated a shit storm).

The spacing between the open/close parentheses and the open and close brackets was another design decision to improve code clarity.  Given the prevalence of use cases for these symbols surrounding "important" code information between them, I felt that the code is more legible when the space is increased between these enclosures and the text contained within.  This is going to be one of the design decisions that most people will feel rather than appreciate as you have done.  It was intentional.

All design decisions are always open for debate.  If anyone can create a convincing argument to the contrary for any decision that we've made in the past, we are always happy to consider changes.

**Comment by burodepeper** [comment]
The vertical alignment of the various brackets is something that needs to be looked into, although it could very well be a hinting issue. I've noticed that the broken pipe (indeed my suggestion) appears a pixel short @13px too.

Your other issues are, as @chrissimpkins mentions, painstakingly debated design decisions, and not implemented purely for visual reasons. But feel free to fork the project, and bake a font entirely to your own preferences.

**Comment by chrissimpkins** [comment]
@burodepeper 👍  good to hear from you David!

I am gearing up for Hack work.  Let me know if you have any free cycles & interest.

**Comment by burodepeper** [comment]
@chrissimpkins Messaged you on Slack!

**Comment by nazar-pc** [comment]
I've actually switched to Hack a few months ago eventually, it is good enough to replace DejaVu Sans Mono. Glad to know that vertical alignment is something you'll take a closer look at 👍

**Comment by burodepeper** [comment]
@nazar-pc Some issues take a while for us to pick up though ; )

**Comment by nazar-pc** [comment]
I'm also maintaining a few Open Source projects and understand how and why it happens

**Comment by chrissimpkins** [comment]
@nazar-pc Good to hear that!  Life outside of FLOSS world has taken me away for some time but there is every intent to get back at it soon.

**Comment by chrissimpkins** [comment]
@nazar-pc Will pick up the conversation with respect to legibility issues involved here:

https://github.com/source-foundry/legible/issues/3

**Comment by chrissimpkins** [comment]
@burodepeper IR associated with curly braces work
