### ISSUE TITLE
Publishing graphic designs featuring the font

### ISSUE THREAD

**Issue by manulicious** [chrissimpkins/Hack#231]
I recently worked on a graphic design using this font for the text in it. It is a private project and I plan to hand out stickers with the design on it on this year's Chaos Communication Congress (that's when I plan to publish the design). I do not want to sell those. Instead, I'd like to publish the design so people can improve it or print their own version.

Since I'm not very confident in understanding font licenses, I'd like to ask if there are any restrictions regarding the licenses I could use to publish the design. I'd like it to be published as CC0/Public Domain or something similar.
Would I be violating any terms in doing so?

**Comment by chrissimpkins** [comment]
Do you intend to distribute the font builds with this in any way so that others can use the fonts to extend this design or is the intent to distribute a rasterized / vector image that includes the glyph shapes when you "publish the design so people can improve it or print their own design"?

Designs that use the glyph shapes within the design are perfectly acceptable and you can license them however you feel appropriate.  The license does not specify any restrictions and you could sell rasterized/vector designs that include the Hack font glyph shapes should you choose based upon my interpretation of the license.  The only potential sticking point as far as I can see is if you sell the "design" with the font binaries distributed along with it.  This is a grey area that treads the ground of selling the fonts (for which there are restrictions in place) 

#### from Hack license

> Neither the Font Software nor any of its individual components, in original or modified versions, may be sold by itself.

#### from Bitstream Vera license

> The Font Software may be sold as part of a larger software package but no copy of one or more of the Font Software typefaces may be sold by itself.

and use/merge/embedding the fonts (not restricted).  Redistribution of the fonts also requires that the original license accompanies the fonts that are distributed to others.

Let me know if any of these specifics apply and we can pull in some other individuals who have greater knowledge of font licensing specifics to see if they can weigh in if it would be helpful.

Good luck with your project!

**Comment by manulicious** [comment]
> Do you intend to distribute the font builds with this in any way so that others can use the fonts to extend this design or is the intent to distribute a rasterized / vector image that includes the glyph shapes when you "publish the design so people can improve it or print their own design"?

Yes, I do want do distribute it in two versions: One pure vector version which doesn't require the font to be installed, and one using the font (either with binary distribution or just linking here) for easier text changes.

> The only potential sticking point as far as I can see is if you sell the "design" with the font binaries distributed along with it.

So, if I understand correctly, selling the design with the font distributed (not even selling the printed result?) would be the only thing possibly leading to violating the terms? That sounds good to me, since I'm not planning to sell anything.

> Redistribution of the fonts also requires that the original license accompanies the fonts that are distributed to others.

Distributing with the license accompanied is not a problem for me. I will possibly link and promote it anyways, since I used the font because I like it that much.

> Good luck with your project!

Thank you very much, they're already printing :)

**Comment by chrissimpkins** [comment]
Good luck and enjoy!

**Comment by manulicious** [comment]
I finally published it now: https://github.com/manulicious/cyberwehr-aufkleber

Please let me know if anything doesn't fit or distribution via git submodule is wrong. Cheers!
