### ISSUE TITLE
symbols appear too small next to alphanumerical characters

### ISSUE THREAD

**Issue by Fandekasp** [chrissimpkins/Hack#248]
First off, thank you very much for your hard work, I've been enjoying Hack for more than a year now.

There's something that's been bothering me for a while though, and it's about symbols. While I'd love to write "→" instead of "->" in my files, the → char just appears too small and doesn't look good. Same for ⇒ and any other composed symbol.

I've also just switched my zsh prompt to [Alpharized](https://github.com/NicoSantangelo/Alpharized), and it became even more appearant with the clock symbol:
![2017-04-23_12-33-14](https://cloud.githubusercontent.com/assets/260983/25310526/21849c40-2821-11e7-8416-87f333d4a3bd.png)

Zooming:
![2017-04-23_12-33-36](https://cloud.githubusercontent.com/assets/260983/25310527/25d0def8-2821-11e7-9dab-d7f19b366ab1.png)

As you can see in the first screenshot with my normal resolution (Hack 12 on 3200x1800 hdpi), the text is readable, but the arrow barely, and the watch doesn't look like anything.

I wish I could change the font size only for symbols.. No idea how could I improve this situation, and what other people are experiencing regarding symbols. Any recommendation will be appreciated.

Thank you!

**Comment by chrissimpkins** [comment]
Unfortunately, I think that this is likely a shortcoming of the fact that this is a fixed width typeface.  There is not a great deal of width to create symbol glyphs in a way that distinguishes them from surrounding glyphs.

For example, if you compare the watch glyph with any of the numerals to the right of it, it is using the same fixed glyph width (I can check but likely to its maximum) in order to render the glyph.  It also uses most of the vertical box.  Happy to take a look at this to see if we can improve upon it if you can provide examples from other fonts that do this well.

**Comment by Fandekasp** [comment]
I'm afraid I won't have time to look into see anytime soon, but I'll keep this in my todo-list, thanks for the reply

**Comment by chrissimpkins** [comment]
No worries.  Feel free to reopen if you want to work on it.
