### ISSUE TITLE
[JetBrains, Java Renderer] Crazy letter spacing in PhpStorm

### ISSUE THREAD

**Issue by josipjelic** [chrissimpkins/Hack#59]
Just tried using Hack for coding but letter spacing is just crazy. Using PhpStrom + Windows 10 + otf or ttf Hack versions. Am I missing something obvious?

Using Hack... both otf and ttf versions 
![crazy_letter_spacing](https://cloud.githubusercontent.com/assets/91408/9597621/f2d6090e-5083-11e5-8c22-6f5c7b8e105e.jpg)

Using Monospaced
![normal_letter_spacing](https://cloud.githubusercontent.com/assets/91408/9597675/744bb97a-5084-11e5-8e2e-3d3a3fda2bd7.jpg)

**Comment by chrissimpkins** [comment]
There have been a number of issues that have come up in the JetBrains editors and they appear to be a result of the way that the Java renderer handles the current iteration of the Hack face.  I am attempting to troubleshoot this through JetBrains and will let you know when I have more information and a release that addresses it.

**Comment by chrissimpkins** [comment]
Mind trying the new v2.011 ttf builds?  I am hoping that this was a metrics table issue related to the glyph that was fixed in this new build. 

[regular](https://github.com/chrissimpkins/Hack/blob/development/build/test_builds/Hack-Regular-2_011.ttf?raw=true)
[bold](https://github.com/chrissimpkins/Hack/blob/development/build/test_builds/Hack-Bold-2_011.ttf?raw=true)
[oblique](https://github.com/chrissimpkins/Hack/blob/development/build/test_builds/Hack-RegularOblique-2_011.ttf?raw=true)
[bold-oblique](https://github.com/chrissimpkins/Hack/blob/development/build/test_builds/Hack-BoldOblique-2_011.ttf?raw=true)

**Comment by josipjelic** [comment]
Thanks, letter spacing now fixed in PhpStrom. Font looking really cool, now let's get used to it :).

**Comment by chrissimpkins** [comment]
great!

**Comment by astiac** [comment]
How do I create spaces between letters?

**Comment by chrissimpkins** [comment]
> How do I create spaces between letters?

You’ll need to adjust the advance width of each glyph in the glyph set.
