### ISSUE TITLE
[JetBrains, Java Renderer] Display errors in PhpStorm when bold+italic

### ISSUE THREAD

**Issue by Estigy** [chrissimpkins/Hack#60]
Not sure if this is a Hack Font issue or a problem on the PhpStorm side...

PhpStorm (latest version, 9.0.2) displays PHP identifier like __NAMESPACE__ in bold and italic. This ends up displaying as ¯¯N~MESP~CE¯¯.

**Comment by txptr** [comment]
Same here.

**Comment by chrissimpkins** [comment]
Received report via Twitter that a workaround on the JetBrains editors is to turn off the bold highlighting.  
![cn0sfrmwgaan_z8](https://cloud.githubusercontent.com/assets/4249591/9607443/32d4429c-5097-11e5-9ed9-be84e19c677e.png)

Clearly that may not be of interest to you if you like the bold highlighting, but I link it for any who wants to make this issue go away until it is resolved.  

Another message that there is a JetBrains bug report dealing with this:

https://youtrack.jetbrains.com/issue/IDEA-138241

in which they point the finger at Java:

https://bugs.openjdk.java.net/browse/JDK-8078382

More info when available.  I will follow these issues.

**Comment by petejohanson** [comment]
Note: The same thing *seems* to render fine on my Fedora Workstation 22 instance of WebStorm, but fails on Windows 7 with Intellij IDEA.

**Comment by chrissimpkins** [comment]
Will you please give these new builds a try?  I've updated the name tables and adjusted the font names based upon what is currently recommended for cross-platform support.  Let's see if this addresses this issue.

**Download Links**
[Regular](https://github.com/chrissimpkins/Hack/blob/development/build/test_builds/2_012/Hack-Regular.ttf?raw=true)
[Bold](https://github.com/chrissimpkins/Hack/blob/development/build/test_builds/2_012/Hack-Bold.ttf?raw=true)
[Italic](https://github.com/chrissimpkins/Hack/blob/development/build/test_builds/2_012/Hack-Italic.ttf?raw=true)
[BoldItalic](https://github.com/chrissimpkins/Hack/blob/development/build/test_builds/2_012/Hack-BoldItalic.ttf?raw=true)

**Comment by davemerrill** [comment]
Ended up here after seeing problems with bold/italic characters in IntelliJ IDEA, as others have reported. Specifically, colons rendered as semicolons, and left and right parens appeared to show as some sort of ligature. That's not necessarily an exhaustive list, just the first ones I saw, which were so alarming initially I bailed on Hack completely. Have to trust my editor, you know : )

However, I'm pleased to report that after installing 2.0.12-ttf, all is well! Haven't seen any strangeness at all. I can also say that when I had switched back to Consolas, it definitely seemed less gut-level readable to me than Hack.

I'm on Windows 7 Pro SP 1, IDEA Ultimate IU-141.2552.1

(FYI, I have IDEA set to size 11, and to approximately match Consolas' line height, I have to set Line height to .9. Wider line spacing may help readability, but balanced against seeing more on the screen, I go for the tighter spacing.)

Thank you for this!

**Comment by chrissimpkins** [comment]
@davemerrill Thanks for this feedback Dave.  I'm glad that it is working.  This will be merged into the master branch as the current release by tomorrow.  Please let me know if you find any other issues in the JetBrains editors.  I am still working on a few other problems that have come up in their editors.

**Comment by Paul-v-H** [comment]
Works for me. Thanks.

In the previous version, in italic (not bold), the underscores sometimes became spaces in IntelliJ until you hovered the mouse over the word. Then it became an underscore. That problem has disappeared as well.

**Comment by chrissimpkins** [comment]
@Paul-v-H Excellent.  This appears to have been the source of a number of problems.  Thanks for that feedback.  I intend to merge this into the master branch as the current release later today.

**Comment by txptr** [comment]
Looks good. Only "bold" PHP Doc Tags are messed. Normally it should display an @-sign (@return ...) but in bold the @-sign is messed up.

**Comment by chrissimpkins** [comment]
@txptr You are using version 2.012 or higher of Hack?  What are you seeing in place of the @ symbol?

Is anyone else seeing this problem with the @ character in the bold v2.012 development build or the new v2.013 release?

**Comment by txptr** [comment]
@chrissimpkins now it's getting weird. Some seconds ago I tried to activate bold again for PHP Doctags to copy/paste the wrong character from yesterday and now the @-character is displayed correctly...
Thank you so far

**Comment by davemerrill** [comment]
@-sign is fine here, plain and bold italic. (Those are really common formats in my current setup, not sure I have anything set to plain italic.) Copied and pasted it with no problems too.

This is with 2.0.12-ttf, Win 7 Pro SP 1, IDEA Ultimate IU-141.2552.1.

Only odd thing so far is that when I went to double-check the version of Hack I had installed, the Font Version column in the Fonts folder is blank. Not super critical, maybe an artifact of this not yet being a real release (I think), but thought you'd want to know.

**Comment by petejohanson** [comment]
Used the download links from your comments, and working fine here now, Win 7 + IDEA 14.1.4. So far no rendering problems I've seen.

**Comment by chrissimpkins** [comment]
@davemerrill : 

> Only odd thing so far is that when I went to double-check the version of Hack I had installed, the Font Version column in the Fonts folder is blank.

Version number should still show as 2.012 in that build.  This is a font version column in the directory listing for the font on Windows?  I am not familiar with this.

**Comment by davemerrill** [comment]
![hack missing version in fonts dir](https://cloud.githubusercontent.com/assets/664423/9741827/a0e21672-562a-11e5-960e-a4df169a9b2f.PNG)

Screenshot attached. That's not the default view. I switched the "control panel" (really a directory) to Detail view, went into Choose Details (pick columns really), and checked Font Version. Not super important I'd think, most people won't notice, I only saw it because I wanted to do exactly this, check its version.

That said, it probably does mean there's a missing resource of some kind that Windows is expecting. I'm not a font dev or expert by any means, so that's really all I know. Did a quick googling and learned nothing, maybe didn't hit the magic query, "font version resource" isn't super specific.

**Comment by davemerrill** [comment]
Just discovered that it does display correctly if you open the Preview dlg for the font, which seems to include the equivalent of showing its Properties. (Shows as a single font with four variations, but all four variants Previews open at once.) 

Not sure why the version shows here but not in the list.

![hack font preview shows version](https://cloud.githubusercontent.com/assets/664423/9742064/fb124fda-562b-11e5-8425-502c1bd945b5.PNG)

**Comment by chrissimpkins** [comment]
Do any other non-system fonts show the version number in that column?  I am assuming those others are system fonts.

**Comment by davemerrill** [comment]
Hmmm, good question, but one that I can't answer directly, since I dn't know how to definitively know which of the fonts on my system are "system" ones. 

But I can tell you that there's a mix of haves and have-nots, including among ones I'm pretty much certain are system. Comic Sans MS, Consolas, don't show a version number in that view, for instance, and they're both specifically credited to Microsoft.

Interestingly, a number of Microsoft fonts appear to have been modified 8/12/2014, and most of those don't have versions.

So my person conclusion is that support for this appears to be optional (read spotty), and I wouldn't worry about it. Sorry for complicating your life. I just happened to see it, nothing more.

Sideshow:  I guess maybe I'm a bit touchy about missing version info, since a lot of the music software plugins I use don't have any. It's impossible to tell if you have the latest without starting up a host program, instantiating the plugin, and looking at its UI. Ironically, at that point, you can't actually update it it because it's in use. It always struck me that those music devs were just missing a simple build step that would make windows Properties dlgs able to see their version info, one time setup and it's done. 

But this font thing is clearly different. There appear to be at least two different official version info resources, for whatever reason. The Mysteries of Microsoft, yet again.

As you were...

**Comment by chrissimpkins** [comment]
No worries at all and thanks for all of that info.  Trying to understand it in case the issue comes up again.

**Comment by chrissimpkins** [comment]
@txptr possibly a font caching issue.  Let me know if you have any other issues.

**Comment by txptr** [comment]
@chrissimpkins so far everything looks good. Yesterday I had some problems with underscores but they are gone now. Thanks again.

**Comment by chrissimpkins** [comment]
@txptr great, thank you very much
