### ISSUE TITLE
8pt Colon

### ISSUE THREAD

**Issue by MaxKh** [chrissimpkins/Hack#66]
-= += <= >= -> -<
Looks great compared to DejaVu

It's time to fix := 

![screenshot_2015-09-01_16-41-28](https://cloud.githubusercontent.com/assets/4003147/9605798/6ee75ef0-50c8-11e5-8759-d9d800b869db.png)
(SublimeText3, Linux)

**Comment by chrissimpkins** [comment]
Definitely will include this fix.  Thanks for pointing it out.

**Comment by manuel-uberti** [comment]
In reference to this https://github.com/chrissimpkins/Hack/issues/100#issuecomment-141976230

I too see the issue with ```:=```. I think raising ```:``` should be enough.

**Comment by chrissimpkins** [comment]
This issue will be fixed in the next release.

<img width="682" alt="colon" src="https://cloud.githubusercontent.com/assets/4249591/10091150/5b47216a-6305-11e5-97ca-8d50ad05eb19.png">

It looks slightly off c/w the equal sign, but (1) it is difficult to make out at small sizes; (2) I can't go higher or it does not look properly aligned next to lowercase alphabetic characters.  

Hope to have the release out in the next few days.

**Comment by MaxKh** [comment]
I'm sure that it will be OK.
Thanks for your work, Chris

**Comment by chrissimpkins** [comment]
@MaxKh thanks for the report.  I never noticed this.

**Comment by chrissimpkins** [comment]
Fixed as of v2.015.  Thanks for the report!
