### ISSUE TITLE
Glyph request: · / U+00B7 / &middot;

### ISSUE THREAD

**Issue by beaugunderson** [chrissimpkins/Hack#70]
Present in the DejaVu family of fonts but not in Hack.

It's common among vim users as the value for `listchars=trail:·` as suggested [here](http://usevim.com/2013/02/27/understanding-listchars/) (among other places).

[More information on the unicode character itself.](http://graphemica.com/%C2%B7)

**Comment by chrissimpkins** [comment]
This is a definite bug Beau.  I apologize about this.  We addressed it in issue #27 and there is a build available in that thread that includes a fix.  It will be part of the next release.  Given the prevalence of issues across editors, I may push this as a bug fix alone.  I was planning to include a few more changes before the next release but it seems to be causing a number of issues across editors because it is used to indicate whitespace/invisible chars.

Thanks again.

**Comment by beaugunderson** [comment]
Oops, didn't see this had been reported already! Thanks for the quick response though, and for the font itself--I never thought I'd switch from DejaVu Sans Mono. :)

**Comment by chrissimpkins** [comment]
No problem at all.  Great to hear that it's working for you.  Thanks for the report.
