### ISSUE TITLE
Build process

### ISSUE THREAD

**Issue by legovini** [chrissimpkins/Hack#85]
Hi,

To ease the process of integration of the Hack font in Debian (and probably other distribution) it is important to define a build process that can run on GNU/Linux distributions. At the moment I can't find enough information about it.

Could you please document the process a bit more, so I can try to rebuild the fonts on my system?

Thank you,

Paride

**Comment by chrissimpkins** [comment]
To clarify, do you mean that you want to rebuild the fonts from source or that you would like clarification on which repository build files are appropriate for release?

If you simply intend to track release ttf or otf builds, then you should stick with those in the build directory of the master branch.  The builds in any other branch of the repository should be considered test builds and unsuitable for general release.  I intend to incorporate changes made in these development builds into releases for general use at which point they will be merged in the master branch with the same file name that is currently used.  Every release for general distribution will carry a new version number.

Building your own fonts for release under the Hack name could lead to issues with the license.  I am in discussion with a SIL representative about a number licensing issues and hope to provide clarification and additional information about this in coming weeks at which point I will make sure that this is explicit for anyone who would like to do this.  The sticking point is that post-build hinting is a significant enough modification to change the display of the typeface on the screen and, as such, would require a change in the name of the typeface under the current license.  We can script the ttfautohint for builds, but we would need to find a way to ensure that the same version of this external dependency is used because the hint/instruction sets may, and likely will, differ between ttfautohint builds.  

The SIL FAQ goes into detail about this issue in their [discussion of reserved font names](http://scripts.sil.org/cms/scripts/page.php?item_id=OFL_web_fonts_and_RFNs#cade8337).  

Here is the text that I am referring to:

```
...hinting can significantly alter the appearance and character of a font, and what some people would consider an improvement others might consider a loss of character. Since responses to these changes are so subjective, it is impossible to guarantee that the font meets the requirements of FE. While in most cases hinting would meet the quality requirement for FE, there is no way to guarantee it, so hinting or rehinting would generally need to be considered a Modified Version for which RFN restrictions apply.
```

It is a bit of a grey area that we will need to discuss in more detail if this is your intent.  I have absolutely no intention of interrupting redistribution of the fonts, this is an issue of quality assurance.   Let's continue the discussion.

**Comment by legovini** [comment]
I speak about building the font from source. I get the point about the reserved name and the difficulty in reproducing the exact font named Hack. 

I see a possible solution: I could still distribute the original font, without rebuilding it, but the Debian source package contains enough information about how to build a font from it. In this way the source files are meaningful for Debian (or whatever) user: they are linked to the ttf/otf files by a clear process. It will be made clear (by the copyright file or by an more explicit warning) that these rebuilt versions shall not be distributed under the Hack name.

Do you see this as a possible solution?
I'll ask the Debian font mentors about what they think about it. To be honest I don't know how stringent the requirement for a clear compiling process is.

**Comment by chrissimpkins** [comment]
Do you have any documentation about the Debian package requirements that you could link?

**Comment by legovini** [comment]
It's something that came out in my "intent to package" Debian bug:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=797627

and consequently in the pkg-fonts-devel mailing list:

https://lists.alioth.debian.org/pipermail/pkg-fonts-devel/2015-September/thread.html

Paride

**Comment by legovini** [comment]
This is the current point:

https://lists.alioth.debian.org/pipermail/pkg-fonts-devel/2015-September/016263.html

If I get it correctly, the idea is to show how to build a font from "source", but it is perfectly fine to distribute as "Hack" the official versions only. I would also be curious to see how a font is built.

Do you see any licensing problem with this?
Is there any documentation about how Hack is built from the UFO files?

**Comment by chrissimpkins** [comment]
The ttf and otf builds are performed with a GUI application (FontLab Studio, OS X version).   PostScript hinting is added to the otf files at the time of the build.   A post-build TrueType instruction set is added to the ttf files with ttfautohint.  The UFO source files are current with the release version in the master branch.  This is a broadly supported typeface source format that can be used to create derivative typefaces in most modern font editors (including FontForge, FontLab Studio, Glyphs, & Robofont).  We would have to look into this in more detail, but I suspect that we could come up with a way to script the ttf build through FontForge and then add the TrueType instructions with ttfautohint on Debian systems.

I noticed that there was mention of the tools directory.  The contained tools are not necessary for the build and can be excluded from the Debian package.  I may remove this directory altogether.  The current tools were placed there as a starting point to create a subsetting tool that would target web font users.  A better approach will be to create a separate repository for this optional tool.

I don't anticipate a licensing issue with the release of the official builds from this repository.  If you intend to package this so that the typeface is generated from the source files on users' systems, we will need to come up with a build workflow that is supported on Debian and manually confirm that the build files do not differ in appearance from the builds released on the repository.

**Comment by chrissimpkins** [comment]
OK to close this issue?

**Comment by legovini** [comment]
Agreed

**Comment by chrissimpkins** [comment]
@legovini where are we with this package?  New build release coming today.  Would you like to discuss further?  You still planning to move forward with this?

**Comment by legovini** [comment]
@chrissimpkins The package is almost ready, now I'll upgrade it with Hack 2.015 and with the new licensing details. After this I'll submit it to the official Debian developers and wait for feedback. I'll let you know how it ends.

**Comment by chrissimpkins** [comment]
The release files are available in compressed tar.gz archives now.  Interested in discussing this package further in Slack?  I am interested I learning about the issues involved (build, licensing) in Linux packaging.

**Comment by legovini** [comment]
@chrissimpkins Good news: the package got accepted in Debian! It's actually these three packages:

https://packages.debian.org/sid/fonts-hack-ttf
https://packages.debian.org/sid/fonts-hack-otf
https://packages.debian.org/sid/fonts-hack-web

I never used Slack, but I can give it a try. Keep in mind that there is no "Linux packaging", as different Linux distributions have different packaging systems, guidelines and license requirements. What I did is specific for Debian (and its derivatives).

**Comment by chrissimpkins** [comment]
@legovini that is fantastic.  Thank you so much for all of your efforts to prepare these and see this through.  If you send me your email address I can invite you to the Slack account to discuss some of the package specific issues further.  You can reach me at chris@sourcefoundry.org
