### ISSUE TITLE
Underscore spacing

### ISSUE THREAD

**Issue by alimsky** [chrissimpkins/Hack#97]
It is probably to wide space on the right
and it doesn't feel bold enough. (WebStorm, font-size: 12px)
![image](https://cloud.githubusercontent.com/assets/626871/9784279/8fcde11e-57aa-11e5-8f59-162df0704728.png)

**Comment by chrissimpkins** [comment]
Noted.  I will take a look at this and get back to you.

**Comment by chrissimpkins** [comment]
Any thoughts on the vertical alignment relative to the alphabetic glyphs (and any other glyphs that they are displayed near for that matter)?

**Comment by alimsky** [comment]
Yeah, it's a bit too low. I think it should be higher by own height.
![screen-shot-2015-09-13-at-10 28 01-pm](https://cloud.githubusercontent.com/assets/626871/9838872/b71f4d82-5a68-11e5-9fa2-dd1852297280.jpg)

**Comment by chrissimpkins** [comment]
The position of the underscore is too low in the source and it is off center. I will correct these and plan for this change to be in the next release.

Any thoughts on the vertical width of the stroke?  Does it seem too narrow to you?

**Comment by alimsky** [comment]
It might be rendering in this particular font size. So, in case you increase to visually match in my case it might be too bold in other font sizes / different platforms. So, it's your call here. I vote for increase though.

**Comment by chrissimpkins** [comment]
Will try to have something that we can try soon.

**Comment by lots0logs** [comment]
I know its a personal preference, but I don't like the way there is extra space between two underscore characters. I prefer it to appear as though they are connected (best way I can explain it, sorry).

Liberation Mono:
![2015-09-19_01-43-52-am](https://cloud.githubusercontent.com/assets/4675662/9975003/376ebba2-5e70-11e5-8d8c-3d2cca89ee39.png)

Hack:
![2015-09-19_01-44-27-am](https://cloud.githubusercontent.com/assets/4675662/9975009/4f1bc948-5e70-11e5-8e8c-671d801ba79f.png)

**Comment by chrissimpkins** [comment]
@lots0logs It's definitely a style issue Dustin.  When we correct the centering, we can try to go a bit wider on the glyph itself but I suspect that there will be others out there who like to see the characters for what they are and not as a single glyph (almost a ligature in the Liberation Mono example that you show, it's difficult for me to make those out as separate glyphs).  As we test these changes, let's try a few width iterations.

You might want to check out some of the excellent fonts out there that include ligatures (for those who do not know, this is taking two or more characters and combining them into a different, commonly single glyph shape).  There are typefaces like Monoid and Fira Code that create attractive ligatures from various character combinations in code.  These are great in working fonts but I have concerns about use in a general purpose source code font (one that is aimed at use outside of the editor for web, print, presentations, etc as well) like this one because you eliminate information in the characters when you create ligatures.  We are discussing this over in #35 if you'd like to follow or add your thoughts.

**Comment by chrissimpkins** [comment]
New test build v2.014 is now available that addresses these issues.  I centered the glyphs, made them slightly larger in the vertical dimension, oriented them closer to the baseline, and adjusted the overall vertical metrics of the fonts.  @lots0logs - I increased the width of the glyphs based upon your suggestion.  The space is slightly apparent still (intentionally) but hopefully brings this closer in line with what you are looking for with the appearance.  

Downloads are available in #111

**Comment by burodepeper** [comment]
My two €-cents:
- I'd like the underscore to be the same width/height as the dash (ie, I'd like to be able to count them)
- I'd like it to rest about its own height underneath the baseline. Or perhaps, directly under the baseline.

**Comment by chrissimpkins** [comment]
@burodepeper Mind posting a screenshot with the new v2.014 test build and the text size that you are using?

**Comment by burodepeper** [comment]
![schermafbeelding 2015-09-21 om 18 33 59](https://cloud.githubusercontent.com/assets/3703530/9997972/59a213ce-608f-11e5-9f36-633f8ffe1124.png)
at `14px`

**Comment by chrissimpkins** [comment]
@burodepeper I increased the spacing between the underscore glyphs for the v2.015 release.  Not quite as wide as they were before that build, but the space is more apparent than in the v2.014 test build.  This is definitely a glyph where we can consider some alternates as we develop a patch script.

Thanks for this issue report.
